baseURL = 'https://daman-game.world'  
languageCode = 'en-IN'
title = 'Daman Games'
defaultContentLanguage = 'en'

[build]
  writeStats = true

[params.auth]
  showButtons = true          # Hi盻㌻/蘯ｩn buttons
  loginText = "DAMAN GAME LOGIN"     # Text button ﾄ惰ハg nh蘯ｭp  
  loginUrl = "https://damanclub.in/#/register?invitationCode=2488315945508" # Link ﾄ惰ハg nh蘯ｭp
  registerText = "DAMAN GAME REGISTER"    # Text button ﾄ惰ハg kﾃｽ
  registerUrl = "https://damanclub.in/#/register?invitationCode=2488315945508" # Link ﾄ惰ハg kﾃｽ
  loginStyle = "default"      # "default", "outline", "ghost"
  registerStyle = "default"   # "default", "outline", "ghost"
  buttonSize = "md"          # "sm", "md", "lg"
  mobileDisplay = "show"      # "show", "hide", "icons"
  loginTarget = "_self"       # "_self", "_blank"
  registerTarget = "_self"    # "_self", "_blank"

[taxonomies]
  category = 'categories'
  tag_display = "tag_displays"
  tag = 'tags'
  game_type = 'game_types'
  difficulty = 'difficulties'

[permalinks]
  blog = '/blog/:slug/'
  tags = '/tag/:slug/'

# Category Pages Configuration
[params.categories]
  [params.categories.blog]
    title = "Daman Games's Blog"
    description = "Discover the latest gaming tips, reviews, and strategies at Daman Games Blog. Level up your gaming experience with expert insights and exclusive content."
    icon = "堂"
    color = "bg-blue-600"
   
[params]
  description = 'Play exciting online games at Daman Games! Enjoy slots, casino games, and more with secure gameplay, instant withdrawals, and 24/7 support.'
  author = 'Daman Games Team'
  logo = '/images/daman-games.webp'
  favicon = '/images/daman-games-favicon.png'
  ogImage = '/images/daman-games-og.webp'
  
  # Social Media
  facebook = 'https://facebook.com/daman-games-world'
  twitter = 'https://twitter.com/daman-games-world'
  youtube = 'https://youtube.com/@daman-games-world'
  
  # Gaming specific
  totalGames = '1000+'
  totalPlayers = '500K+'
  totalPlays = '1M+'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menu Configuration
[[menu.main]]
  name = "Daman Games Homepage"
  url = "https://daman-game.world"
  weight = 10
  pre = "匠"

[[menu.main]]
  name = "Daman Games's Blog"
  url = "/blog/"
  weight = 40
  pre = "堂"
